table 'Test Import 1 & 3'
	lineageTag: 895b007e-4655-444e-856e-efa2fd4d73cb

	refreshPolicy
		policyType: basic
		rollingWindowGranularity: year
		rollingWindowPeriods: 1
		incrementalGranularity: day
		incrementalPeriods: 1
		sourceExpression =
			let
			    // Connects to the root contents of the SharePoint site using the provided URL
			    #"Accessed SharePoint Contents" = SharePoint.Contents(SharePoint_URL),
			    // Drills into the Documents folder within the lakehouse content
			    #"Drilled Into Documents Folder" = #"Accessed SharePoint Contents"{[Name="Documents"]}[Content],
			    // Filters out any items in the Documents folder that have the name "2"
			    #"Filtered Out Name 2" = Table.SelectRows(#"Drilled Into Documents Folder", each ([Name] <> "2")),
			    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Out Name 2",{"Name", "Content"}),
			    // Expands the Content and Name columns for easier access to underlying data
			    #"Expanded Content And Name Columns" = Table.ExpandTableColumn(#"Removed Other Columns", "Content", {"Content", "Date created", "Name"}, {"Content.1", "Date created", "Name.1"}),
			    // Update Date Create type
			    #"Changed Date Created Type" = Table.TransformColumnTypes(#"Expanded Content And Name Columns",{{"Date created", type datetime}}),
			    // Keeps only rows where the created date falls within the defined date range
			    #"Kept Rows By Date Range" = Table.SelectRows(#"Changed Date Created Type", each [Date created] > RangeStart and [Date created] <= RangeEnd),
			    // Selects just the columns for content and name from the filtered data
			    #"Kept Content And Name Columns" = Table.SelectColumns(#"Kept Rows By Date Range",{"Content.1", "Name.1"}),
			    // Filters out files marked as hidden within their attributes
			    #"Excluded Hidden Files" = Table.SelectRows(#"Kept Content And Name Columns", each [Attributes]?[Hidden]? <> true),
			    // Applies a custom function to transform each file's content as needed
			    #"Transformed File Content" = Table.AddColumn(#"Excluded Hidden Files", "Transform File", each #"Transform File"([Content.1])),
			    // Retains only the column resulting from the custom transformation
			    #"Kept Transformed File Only" = Table.SelectColumns(#"Transformed File Content", {"Transform File"}),
			    // Expands the transformed table columns into the main table for analysis
			    #"Expanded Transform File Columns" = Table.ExpandTableColumn(#"Kept Transformed File Only", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
			    // Converts specific columns to appropriate data types for downstream reporting
			    #"Converted Column Types" = Table.TransformColumnTypes(#"Expanded Transform File Columns",{{"project_name", type text}, {"project_description", type text}, {"start_date", type date}, {"end_date", type date}, {"project_manager", type text}, {"project_budget", type text}, {"project_status", type text}, {"client_name", type text}, {"client_email", type text}, {"client_phone", type text}})
			in
			    #"Converted Column Types"

	measure 'Row Count' = COUNTROWS('Test Import 1 & 3')
		formatString: 0
		lineageTag: f8ba4c30-f820-4ef6-87eb-f8b6768edf7e

	column project_name
		dataType: string
		lineageTag: d2ca20c5-1d38-4c85-b61b-3d30281d1820
		summarizeBy: none
		sourceColumn: project_name

		annotation SummarizationSetBy = Automatic

	column project_description
		dataType: string
		lineageTag: 542df1ab-dfd6-45a9-bdf6-887b56c70604
		summarizeBy: none
		sourceColumn: project_description

		annotation SummarizationSetBy = Automatic

	column start_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: e12de29c-a363-4add-87e5-fa83331d4df5
		summarizeBy: none
		sourceColumn: start_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column end_date
		dataType: dateTime
		formatString: Long Date
		lineageTag: 0aa9b344-5a8d-4b99-b0d5-950c30036343
		summarizeBy: none
		sourceColumn: end_date

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column project_manager
		dataType: string
		lineageTag: a905f6b6-f62b-4c0a-b380-fb59bc9e6574
		summarizeBy: none
		sourceColumn: project_manager

		annotation SummarizationSetBy = Automatic

	column project_budget
		dataType: string
		lineageTag: eff71f8f-6199-4fec-a4c0-d1d0b129bdc4
		summarizeBy: none
		sourceColumn: project_budget

		annotation SummarizationSetBy = Automatic

	column project_status
		dataType: string
		lineageTag: 0b2015b0-7cde-479d-b555-1a9b773b470d
		summarizeBy: none
		sourceColumn: project_status

		annotation SummarizationSetBy = Automatic

	column client_name
		dataType: string
		lineageTag: 828b908f-cda5-4742-80c8-611fdf83ebf3
		summarizeBy: none
		sourceColumn: client_name

		annotation SummarizationSetBy = Automatic

	column client_email
		dataType: string
		lineageTag: 2f9362d3-8f04-4cfb-a03f-98af157ded00
		summarizeBy: none
		sourceColumn: client_email

		annotation SummarizationSetBy = Automatic

	column client_phone
		dataType: string
		lineageTag: d1852274-f778-408e-98d8-b75f1d3db5ba
		summarizeBy: none
		sourceColumn: client_phone

		annotation SummarizationSetBy = Automatic

	partition 'Test Import 1 & 3' = m
		mode: import
		source =
				let
				    // Connects to the root contents of the SharePoint site using the provided URL
				    #"Accessed SharePoint Contents" = SharePoint.Contents(SharePoint_URL),
				    // Drills into the Documents folder within the lakehouse content
				    #"Drilled Into Documents Folder" = #"Accessed SharePoint Contents"{[Name="Documents"]}[Content],
				    // Filters out any items in the Documents folder that have the name "2"
				    #"Filtered Out Name 2" = Table.SelectRows(#"Drilled Into Documents Folder", each ([Name] <> "2")),
				    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Out Name 2",{"Name", "Content"}),
				    // Expands the Content and Name columns for easier access to underlying data
				    #"Expanded Content And Name Columns" = Table.ExpandTableColumn(#"Removed Other Columns", "Content", {"Content", "Date created", "Name"}, {"Content.1", "Date created", "Name.1"}),
				    // Update Date Create type
				    #"Changed Date Created Type" = Table.TransformColumnTypes(#"Expanded Content And Name Columns",{{"Date created", type datetime}}),
				    // Keeps only rows where the created date falls within the defined date range
				    #"Kept Rows By Date Range" = Table.SelectRows(#"Changed Date Created Type", each [Date created] > RangeStart and [Date created] <= RangeEnd),
				    // Selects just the columns for content and name from the filtered data
				    #"Kept Content And Name Columns" = Table.SelectColumns(#"Kept Rows By Date Range",{"Content.1", "Name.1"}),
				    // Filters out files marked as hidden within their attributes
				    #"Excluded Hidden Files" = Table.SelectRows(#"Kept Content And Name Columns", each [Attributes]?[Hidden]? <> true),
				    // Applies a custom function to transform each file's content as needed
				    #"Transformed File Content" = Table.AddColumn(#"Excluded Hidden Files", "Transform File", each #"Transform File"([Content.1])),
				    // Retains only the column resulting from the custom transformation
				    #"Kept Transformed File Only" = Table.SelectColumns(#"Transformed File Content", {"Transform File"}),
				    // Expands the transformed table columns into the main table for analysis
				    #"Expanded Transform File Columns" = Table.ExpandTableColumn(#"Kept Transformed File Only", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
				    // Converts specific columns to appropriate data types for downstream reporting
				    #"Converted Column Types" = Table.TransformColumnTypes(#"Expanded Transform File Columns",{{"project_name", type text}, {"project_description", type text}, {"start_date", type date}, {"end_date", type date}, {"project_manager", type text}, {"project_budget", type text}, {"project_status", type text}, {"client_name", type text}, {"client_email", type text}, {"client_phone", type text}})
				in
				    #"Converted Column Types"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

