table Users
	lineageTag: 9b171526-72e2-4e55-bd59-dc5d7609aaaa

	column 'UPN ID'
		dataType: int64
		formatString: 0
		lineageTag: b56be1cd-c6bc-431b-95cc-9d70a991594c
		summarizeBy: count
		sourceColumn: UPN ID

		annotation SummarizationSetBy = Automatic

	column UPN
		dataType: string
		lineageTag: 79d301ff-f25e-4231-972e-274df877b440
		summarizeBy: none
		sourceColumn: UPN

		annotation SummarizationSetBy = Automatic

	partition Users = m
		mode: import
		queryGroup: RLS
		source =
				let
				    Source = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i45WMlTSUcpJSizKTi1ySE4rSU3OyMvPyU/PTC3OyUnWS87PVYrViVYyAqqqysrPyCvOz8OjzBioLAtoUnF2Ji5VsQA=", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"UPN ID" = _t, UPN = _t]),
				    #"Changed Type" = Table.TransformColumnTypes(Source,{{"UPN ID", Int64.Type}, {"UPN", type text}})
				in
				    #"Changed Type"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

