createOrReplace

		table 'Test Import 1 & 3'
			lineageTag: 895b007e-4655-444e-856e-efa2fd4d73cb

			refreshPolicy
				policyType: basic
				rollingWindowGranularity: year
				rollingWindowPeriods: 1
				incrementalGranularity: day
				incrementalPeriods: 1
				sourceExpression =
					let
					    // Connects to the root contents of the SharePoint site using the provided URL
					    #"Accessed SharePoint Contents" = SharePoint.Contents(SharePoint_URL),
					    // Drills into the Documents folder within the lakehouse content
					    #"Drilled Into Documents Folder" = #"Accessed SharePoint Contents"{[Name="Documents"]}[Content],
					    // Filters out any items in the Documents folder that have the name "2"
					    #"Filtered Out Name 2" = Table.SelectRows(#"Drilled Into Documents Folder", each ([Name] <> "2")),
					    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Out Name 2",{"Name", "Content"}),
					    // Expands the Content and Name columns for easier access to underlying data
					    #"Expanded Content And Name Columns" = Table.ExpandTableColumn(#"Removed Other Columns", "Content", {"Content", "Date created", "Name"}, {"Content.1", "Date created", "Name.1"}),
					    // Update Date Create type
					    #"Changed Date Created Type" = Table.TransformColumnTypes(#"Expanded Content And Name Columns",{{"Date created", type datetime}}),
					    // Keeps only rows where the created date falls within the defined date range
					    #"Kept Rows By Date Range" = Table.SelectRows(#"Changed Date Created Type", each [Date created] > RangeStart and [Date created] <= RangeEnd),
					    // Selects just the columns for content and name from the filtered data
					    #"Kept Content And Name Columns" = Table.SelectColumns(#"Kept Rows By Date Range",{"Content.1", "Name.1"}),
					    // Filters out files marked as hidden within their attributes
					    #"Excluded Hidden Files" = Table.SelectRows(#"Kept Content And Name Columns", each [Attributes]?[Hidden]? <> true),
					    // Applies a custom function to transform each file's content as needed
					    #"Transformed File Content" = Table.AddColumn(#"Excluded Hidden Files", "Transform File", each #"Transform File"([Content.1])),
					    // Retains only the column resulting from the custom transformation
					    #"Kept Transformed File Only" = Table.SelectColumns(#"Transformed File Content", {"Transform File"}),
					    // Expands the transformed table columns into the main table for analysis
					    #"Expanded Transform File Columns" = Table.ExpandTableColumn(#"Kept Transformed File Only", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
					    // Converts specific columns to appropriate data types for downstream reporting
					    #"Converted Column Types" = Table.TransformColumnTypes(#"Expanded Transform File Columns",{{"project_name", type text}, {"project_description", type text}, {"start_date", type date}, {"end_date", type date}, {"project_manager", type text}, {"project_budget", type text}, {"project_status", type text}, {"client_name", type text}, {"client_email", type text}, {"client_phone", type text}})
					in
					    #"Converted Column Types"

			measure 'Row Count' = COUNTROWS('Test Import 1 & 3')
				formatString: 0
				lineageTag: f8ba4c30-f820-4ef6-87eb-f8b6768edf7e

			column project_name
				dataType: string
				lineageTag: d2ca20c5-1d38-4c85-b61b-3d30281d1820
				summarizeBy: none
				sourceColumn: project_name

				annotation SummarizationSetBy = Automatic

			column project_description
				dataType: string
				lineageTag: 542df1ab-dfd6-45a9-bdf6-887b56c70604
				summarizeBy: none
				sourceColumn: project_description

				annotation SummarizationSetBy = Automatic

			column start_date
				dataType: dateTime
				formatString: Long Date
				lineageTag: e12de29c-a363-4add-87e5-fa83331d4df5
				summarizeBy: none
				sourceColumn: start_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column end_date
				dataType: dateTime
				formatString: Long Date
				lineageTag: 0aa9b344-5a8d-4b99-b0d5-950c30036343
				summarizeBy: none
				sourceColumn: end_date

				annotation SummarizationSetBy = Automatic

				annotation UnderlyingDateTimeDataType = Date

			column project_manager
				dataType: string
				lineageTag: a905f6b6-f62b-4c0a-b380-fb59bc9e6574
				summarizeBy: none
				sourceColumn: project_manager

				annotation SummarizationSetBy = Automatic

			column project_budget
				dataType: string
				lineageTag: eff71f8f-6199-4fec-a4c0-d1d0b129bdc4
				summarizeBy: none
				sourceColumn: project_budget

				annotation SummarizationSetBy = Automatic

			column project_status
				dataType: string
				lineageTag: 0b2015b0-7cde-479d-b555-1a9b773b470d
				summarizeBy: none
				sourceColumn: project_status

				annotation SummarizationSetBy = Automatic

			column client_name
				dataType: string
				lineageTag: 828b908f-cda5-4742-80c8-611fdf83ebf3
				summarizeBy: none
				sourceColumn: client_name

				annotation SummarizationSetBy = Automatic

			column client_email
				dataType: string
				lineageTag: 2f9362d3-8f04-4cfb-a03f-98af157ded00
				summarizeBy: none
				sourceColumn: client_email

				annotation SummarizationSetBy = Automatic

			column client_phone
				dataType: string
				lineageTag: d1852274-f778-408e-98d8-b75f1d3db5ba
				summarizeBy: none
				sourceColumn: client_phone

				annotation SummarizationSetBy = Automatic

			partition 'Test Import 1 & 3' = m
				mode: import
				source =
						let
						    // Connects to the root contents of the SharePoint site using the provided URL
						    #"Accessed SharePoint Contents" = SharePoint.Contents(SharePoint_URL),
						    // Drills into the Documents folder within the lakehouse content
						    #"Drilled Into Documents Folder" = #"Accessed SharePoint Contents"{[Name="Documents"]}[Content],
						    // Filters out any items in the Documents folder that have the name "2"
						    #"Filtered Out Name 2" = Table.SelectRows(#"Drilled Into Documents Folder", each ([Name] <> "2")),
						    #"Removed Other Columns" = Table.SelectColumns(#"Filtered Out Name 2",{"Name", "Content"}),
						    // Expands the Content and Name columns for easier access to underlying data
						    #"Expanded Content And Name Columns" = Table.ExpandTableColumn(#"Removed Other Columns", "Content", {"Content", "Date created", "Name"}, {"Content.1", "Date created", "Name.1"}),
						    // Update Date Create type
						    #"Changed Date Created Type" = Table.TransformColumnTypes(#"Expanded Content And Name Columns",{{"Date created", type datetime}}),
						    // Keeps only rows where the created date falls within the defined date range
						    #"Kept Rows By Date Range" = Table.SelectRows(#"Changed Date Created Type", each [Date created] > RangeStart and [Date created] <= RangeEnd),
						    // Selects just the columns for content and name from the filtered data
						    #"Kept Content And Name Columns" = Table.SelectColumns(#"Kept Rows By Date Range",{"Content.1", "Name.1"}),
						    // Filters out files marked as hidden within their attributes
						    #"Excluded Hidden Files" = Table.SelectRows(#"Kept Content And Name Columns", each [Attributes]?[Hidden]? <> true),
						    // Applies a custom function to transform each file's content as needed
						    #"Transformed File Content" = Table.AddColumn(#"Excluded Hidden Files", "Transform File", each #"Transform File"([Content.1])),
						    // Retains only the column resulting from the custom transformation
						    #"Kept Transformed File Only" = Table.SelectColumns(#"Transformed File Content", {"Transform File"}),
						    // Expands the transformed table columns into the main table for analysis
						    #"Expanded Transform File Columns" = Table.ExpandTableColumn(#"Kept Transformed File Only", "Transform File", Table.ColumnNames(#"Transform File"(#"Sample File"))),
						    // Converts specific columns to appropriate data types for downstream reporting
						    #"Converted Column Types" = Table.TransformColumnTypes(#"Expanded Transform File Columns",{{"project_name", type text}, {"project_description", type text}, {"start_date", type date}, {"end_date", type date}, {"project_manager", type text}, {"project_budget", type text}, {"project_status", type text}, {"client_name", type text}, {"client_email", type text}, {"client_phone", type text}})
						in
						    #"Converted Column Types"

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Table

		cultureInfo en-US

			linguisticMetadata = {"Version":"4.1.0","Language":"en-US","Agents":{"Internal":{"Version":"1.1.0"}}}
				contentType: json

		expression SharePoint_URL = "https://kerski.sharepoint.com/sites/DocLibTest" meta [IsParameterQuery=true, Type="Text", IsParameterQueryRequired=true]
			lineageTag: 7a1ae011-3acd-480d-bc25-3329d1fa3596
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Text

		expression Parameter1 = #"Sample File" meta [IsParameterQuery=true, BinaryIdentifier=#"Sample File", Type="Binary", IsParameterQueryRequired=true]
			lineageTag: 0e58629c-ffe0-4206-82fa-9a49b5065a59
			queryGroup: 'Transform File from Test Import 1 & 3\Helper Queries'

			annotation PBI_ResultType = Binary

		expression 'Sample File' =
				let
				    //Connects to the Lakehouse using provided parameters
				    #"Accessed Lakehouse Contents" = SharePoint.Contents(SharePoint_URL),
				    // Connects to the Lakehouse using provided parameters
				    Documents = #"Accessed Lakehouse Contents"{[Name="Documents"]}[Content],
				    #"Filtered Rows" = Table.SelectRows(Documents, each ([Name] <> "2")),
				    #"Expanded Content" = Table.ExpandTableColumn(#"Filtered Rows", "Content", {"Content", "Name"}, {"Content.1", "Name.1"}),
				    #"Removed Other Columns" = Table.SelectColumns(#"Expanded Content",{"Content.1", "Name.1"}),
				    Navigation1 = #"Removed Other Columns"{0}[Content.1]
				in
				    Navigation1
			lineageTag: 6c62e671-4f3e-4ba6-9bfd-02267381ca63
			queryGroup: 'Transform File from Test Import 1 & 3\Helper Queries'

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = Binary

		expression 'Transform Sample File' =
				let
				    Source = Csv.Document(Parameter1,[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"
			lineageTag: e543b7f8-24d6-44a6-a461-78dbe9376f98
			queryGroup: 'Transform File from Test Import 1 & 3'

			annotation PBI_ResultType = Table

		expression 'Transform File' =
				let
				    Source = (Parameter1 as binary) => let
				    Source = Csv.Document(Parameter1,[Delimiter=",", Columns=10, Encoding=1252, QuoteStyle=QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars=true])
				in
				    #"Promoted Headers"
				in
				    Source
			mAttributes: [ FunctionQueryBinding = "{""exemplarFormulaName"":""Transform Sample File""}" ]
			lineageTag: 246a36f3-3f0d-48d3-94cf-ecbbb74d3ce0
			queryGroup: 'Transform File from Test Import 1 & 3\Helper Queries'

			annotation PBI_ResultType = Function

		expression RangeStart = #datetime(2025, 7, 1, 0, 0, 0) meta [IsParameterQuery=true, Type="DateTime", IsParameterQueryRequired=true]
			lineageTag: 089b63fa-1e4b-4be9-9602-8027c27f6095
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = DateTime

		expression RangeEnd = #datetime(2026, 1, 1, 0, 0, 0) meta [IsParameterQuery=true, Type="DateTime", IsParameterQueryRequired=true]
			lineageTag: d43c0bad-3e6b-45df-952f-65e1e2384269
			queryGroup: Parameters

			annotation PBI_NavigationStepName = Navigation

			annotation PBI_ResultType = DateTime

		queryGroup Parameters

			annotation PBI_QueryGroupOrder = 2

		queryGroup 'Transform File from Test Import 1 & 3'

			annotation PBI_QueryGroupOrder = 1

		queryGroup 'Transform File from Test Import 1 & 3\Helper Queries'

			annotation PBI_QueryGroupOrder = 0

		annotation __PBI_TimeIntelligenceEnabled = 0

		annotation PBI_QueryOrder = ["SharePoint_URL","RangeStart","RangeEnd","Test Import 1 & 3","Sample File","Parameter1","Transform Sample File","Transform File"]

		annotation PBI_ProTooling = ["TMDLView_Desktop"]

