DEFINE             
			    VAR _Functions =
                    SELECTCOLUMNS(
                        INFO.USERDEFINEDFUNCTIONS(),
                        "ID",          [ID],
                        "Name",        [Name],
                        "Description", [Description]
                    )
                VAR _ImpersonatedUser =
                    SELECTCOLUMNS(
                        FILTER(INFO.ANNOTATIONS(), [Name] = "PQLAssert_ImpersonatedUserName"),
                        "ID",               [ObjectID],
                        "PQLAssert_ImpersonatedUserName", [Value]
                    )
                VAR _AllFunctions =
                    NATURALLEFTOUTERJOIN(
                        NATURALLEFTOUTERJOIN(
                            _Functions,
                            _ImpersonatedUser
                        ),
                        _ImpersonatedUser
                    )
					
                EVALUATE
                    FILTER(INFO.ANNOTATIONS(), [Name] = "PQLAssert_ImpersonatedUserName")